= SASS - Syntactically Awesome Style Sheets
Swagat Srichandan <swagatchandan@gmail.com>
v1.0, 9/13/2018

Sass is an extension of CSS that adds power and elegance to the basic language. +
It allows you to use __variables__, __nested rules__, __mixins__, __inline imports__, and more, all with a fully CSS-compatible syntax. +
Sass helps keep large stylesheets well-organized, and get small stylesheets up and running quickly, particularly with the help of the Compass style library.

== Sass Basics

=== Preprocessing
Preprocessor helps to  maintain large complex CSS files, allows to use variables, mixins, inheritance.

=== Variables
Sass uses the `$` symbol to make something a variable. +
Below is an example
[source]
----
$font-stack: Helvetica, sans-serif;
$primary-color: #333

body {
  font: 100% $font-stack;
  color: $primary-color
}
----

=== Nesting
Sass will let you nest your CSS selectors in a way that follows the same visual hierarchy of your HTML. +
[source]
----
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
----

=== Partials
A partial is simply a Sass file named with a leading underscore. Something like `_partial.scss`. +
Sass partials are used with the `@import` directive.

=== Imports
Sass builds on top of the current CSS @import but instead of requiring an HTTP request, Sass will take the file that you want to import and combine it with the file you're importing into so you can serve a single CSS file to the web browser.
[NOTE]
CSS has an import option that lets you split your CSS into smaller, more maintainable portions. The only drawback is that each time you use @import in CSS it creates another HTTP request.

Let's say you have a couple of Sass files, `_reset.scss` and `base.scss`. We want to import `_reset.scss` into `base.scss`.
[source]
----
// _reset.scss
html,
body,
ul,
ol {
  margin: 0;
  padding: 0;
}

// base.scss
@import 'reset';

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
----

=== Mixins
A mixin lets you make groups of CSS declarations that you want to reuse throughout your site. +
You can even pass in values to make your mixin more flexible. A good use of a mixin is for vendor prefixes. Here's an example for transform.
[source]
----
@mixin transform($property) {
  -webkit-transform: $property;
  -ms-transform: $property;
  transform: $property;
}

.box { @include transform(rotate(30deg)); }
----

=== Inheritance
Using `@extend` lets you share a set of CSS properties from one selector to another.
[source]
----
/* This CSS will print because %message-shared is extended. */
%message-shared {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}

// This CSS won't print because %equal-heights is never extended.
%equal-heights {
  display: flex;
  flex-wrap: wrap;
}

.message {
  @extend %message-shared;
}

.success {
  @extend %message-shared;
  border-color: green;
}

.error {
  @extend %message-shared;
  border-color: red;
}

.warning {
  @extend %message-shared;
  border-color: yellow;
}
----

=== Operators
Doing math in your CSS is very helpful. Sass has a handful of standard math operators like +, -, *, /, and %. In our example we're going to do some simple math to calculate widths for an aside & article.
[source]
----
.container {
  width: 100%;
}

article[role="main"] {
  float: left;
  width: 600px / 960px * 100%;
}

aside[role="complementary"] {
  float: right;
  width: 300px / 960px * 100%;
}
----
