= Key Concepts

== 1. Principles of REST Architecture

=== 1.1 Addressable Resources

=== 1.2 A Uniform, Constrained Interface

=== 1.3 Representation Oriented

=== 1.4 Communicate Statelessly

=== 1.5 Hypermedia As The Engine Of Application State (HATEOAS)

== 2. JAX-RS Injection

=== 2.1 @PathParam

=== 2.2 @MatrixParam

=== 2.3 @QueryParam

=== 2.4 @FormParam

=== 2.5 @HeaderParam

=== 2.6 @CookieParam

=== 2.7 @Context

=== 2.8 @BeanParam

== 3. Server Responses and Exception Handling

=== 3.1 Default Successful Responses

=== 3.2 Default Error Responses

=== 3.3 Complex Responses

=== 3.4 Returning Cookies

=== 3.5 Status Enum

=== 3.6 Exception Handling

=== 3.7 Exception Mapping

=== 3.8 Exception Hierarchy

== 4. JAX-RS Client

=== 4.1 Client Introduction

=== 4.2 Bootstrapping with Client Builder

=== 4.3 Client and Web Target

=== 4.4 Building and Invoking Request

=== 4.5 Invocation

=== 4.6 Exception Handling

=== 4.7 Configuration Scope

== 5. HTTP Content Negotiation

=== 5.1 Conneg Explained

=== 5.2 Preference Ordering

=== 5.3 Language Negotiation

=== 5.4 Encoding Negotiation

=== 5.5 JAX-RS and Conneg

=== 5.6 Negotiation with URI Patterns

=== 5.7 Leveraging Content Negotiation

=== 5.8 Creating New Media-Types

=== 5.9 Flexible Schema

== 6. HTTP Caching
*Browser cache*, when browser stores some of the static content within the local storage. +
*Proxy cache* (CDNs), when a pseudo-web server cache static content in order to ease load on the main server and serves directly to the client bypassing the main server.

[NOTE]
Any Server URI that can be reached with an HTTP *GET* is a candidate for caching as they are [.underline]#idempotent# and [.underline]#read-only#

[NOTE]
Dynamic Data that are concurrently accessed can also be a candidate for caching.

HTTP defines a set of build-in cache semantics which gives a fine-grained control over caching behavior of both browser and proxy caches.

=== 6.1 Expires Headers
A HTTP Header Response `Expires` tells the browser that it can be cached and for how long. +
The value is a `Date` in the future when the data is no longer valid, incase the date is reached then the data should not be used and be retrieved again from server.

[NOTE]
HTTP/1.0 Specification

Sample Response with `Expires`
[source]
----
HTTP/1.0 200 OK
Content Type: application/xml
Expires: Wed, 26 September 2018 17:30 PM GMT

<customer id="123">...</customer>
----

The code implementation is done using `javax.ws.rs.core.Response` object

.CustomerResource.java

:source-highlighter: pygments
[source, java]
----
@Path("/customers")
public class CustomerResource {

  @Path("{id}")
  @GET
  @Produces("application/xml")
  public Response getCustomers(@PathParam("id") int id) {
    Customer cust = findCustomer(id);
    ResponseBuilder builder = Response.ok(cust, "application/xml");
    Date date = Calendar.getInstance(TimeZone.getTimeZone("GMT"))
                            .set(2018, 9, 26, 17, 30, 0);
    builder.expires(date); // <1>
    return builder.build();
  }
}
----
<1> The method sets the `Expires` header to the string date format the header expects.

=== 6.2 Cache-Control
`Cache-Control` header has more richer explicit control over browser and CDN/proxy caches. +
It has a variable set of  comma-delimited directives that define who can cache, how and for how long.

[NOTE]
HTTP/1.1 Specification, `Expires` is *deprecated*

==== 6.2.1 `private`
The `private` directive states that *no shared intermediary (proxy/CDN)* is allowed to cache the response. +
Only the client caches the data.

==== 6.2.2 `public`
The `public` directive indicates that *any entity* can cache the response.

==== 6.2.3 `no-cache`
The `no-cache` directive indicates the response *should not be cached* by any entity. +
If the data is cached then it should not be used to satisfy a request unless it is revalidated by the server.

==== 6.2.4 `no-store`
The `no-store` directs browser or proxies *not to store cached response on the disk*.

==== 6.2.5 `no-transform`
The `no-transform` *disallows transformation of cached response* _e.g., compressing images,_ by the intermediary proxies.

==== 6.2.6 `max-age`
The `max-age` directive indicates *for how many seconds* the cached response is valid. +
It gets precedence over `Expires` if both are in response.

==== 6.2.7 `s-maxage`
The `s-maxage` directive is similar to `max-age` but specified the *max time a shared, intermediary (proxies) is allowed to hold the cached response*.

=== 6.3 Revalidation and Conditional GETs
