Networking Essentials
=====================
:me: iamswagat

Collection of protocols working together help to moving information or *Data Networking*.

== 1. *OSI* or Open System Interconnection Model
image:https://www.lifewire.com/thmb/OY1lnnhR6g5bNqEqwUYyFyvEXRs=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/Osi-model-jb.svg-57f7b9af3df78c690f6305e8.png[OSI Model]

=== 1.1 Physical Layer
Connects all of our devices together

=== 1.2 Data Link Layer
Protocols connect devices, move traffic within

=== 1.3 Networking Layer
*IP addressing* allows sending and receiving messages

*IP Routing* allows sending message to-fro unique addresses

=== 1.4 Transport Layer
*Transmission Control Protocol* or TCP

=== 1.5 Session Layer
*ICA*

=== 1.6 Presentation Layer
=== 1.7 Application Layer
*Hypertext Transfer Protocol (Secure)* HTTP(S) +
Transferring Data, Client Server Model
Every single Application Layer protocol has a Transport Layer component called "ports" +
E.g., HTTP has default port _80_ in 4th layer and HTTPS has a default port
_443_ in 4th layer thus identifying the layer 7 protocol used via the port number +
*(Secure) File Transfer Protocol* (s)FTP and *Trivial FTP* TFTP +
port: 20 (authentication), 21 (transferring) for FTP +
port: 22 for sFTP also used for SSH +
port: 69 for TFTP +
*Server Message Block* SMB Network file share +
port 445
